/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fDd2G34bQHvh5ANU7bqHFd
// Component: 2rS9lZvVnqgF
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button2 from "../../Button2"; // plasmic-import: H9upVDVV-cSX/component
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: fDd2G34bQHvh5ANU7bqHFd/styleTokensProvider
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic.module.css"; // plasmic-import: fDd2G34bQHvh5ANU7bqHFd/projectcss
import sty from "./PlasmicTestHp.module.css"; // plasmic-import: 2rS9lZvVnqgF/css
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: gwt4vL4rdeSl/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: lMi8Misnr69u/icon

createPlasmicElementProxy;

export const PlasmicTestHp__VariantProps = new Array();

export const PlasmicTestHp__ArgProps = new Array();

const $$ = {};

function PlasmicTestHp__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const styleTokensClassNames = _useStyleTokens();
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__zHprp)}>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))([
              2, 3, 4
            ]).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  className={classNames(projectcss.all, sty.freeBox__dOwXg)}
                  key={currentIndex}
                >
                  <PlasmicImg__
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"40px"}
                    src={{
                      src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgY2xhc3M9Ikljb25fX0ltYWdlLXNjLTF0N2Z2azUtMCBjRlBLZkUiPgogIDxwYXRoIGZpbGw9IiMxNDE4MjQiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTMuMDA1IDNIMTV2MTJIMy4wMDVWM3pNMTQuNSAyMWE2LjUgNi41IDAgMTAwLTEzIDYuNSA2LjUgMCAwMDAgMTN6IiBjbGlwLXJ1bGU9ImV2ZW5vZGQiLz4KPC9zdmc+Cg==",
                      fullWidth: 150,
                      fullHeight: 150,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(projectcss.all, sty.freeBox___0R64T)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__wE5Sw
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Services"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__gHae5
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Features"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___5X8Kt
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Company"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__gz3U6
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Contact"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__f3CZ
                      )}
                      href={"https://www.plasmic.app/"}
                      platform={"react"}
                    >
                      {"Log in"}
                    </PlasmicLink__>
                    <Button2
                      data-plasmic-name={"button2"}
                      data-plasmic-override={overrides.button2}
                      className={classNames("__wab_instance", sty.button2)}
                      color={"black"}
                      end={
                        <ChevronDownIcon
                          className={classNames(projectcss.all, sty.svg__p9TZk)}
                          role={"img"}
                        />
                      }
                      label={
                        <div
                          data-plasmic-name={"text"}
                          data-plasmic-override={overrides.text}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text
                          )}
                        >
                          {"Sign up"}
                        </div>
                      }
                      start={
                        <CircleIcon
                          className={classNames(projectcss.all, sty.svg___2EvO)}
                          role={"img"}
                        />
                      }
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "img", "button2", "text"],
  img: ["img"],
  button2: ["button2", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicTestHp__ArgProps,
          internalVariantPropNames: PlasmicTestHp__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicTestHp__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTestHp";
  } else {
    func.displayName = `PlasmicTestHp.${nodeName}`;
  }
  return func;
}

export const PlasmicTestHp = Object.assign(
  // Top-level PlasmicTestHp renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    button2: makeNodeComponent("button2"),
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicTestHp
    internalVariantProps: PlasmicTestHp__VariantProps,
    internalArgProps: PlasmicTestHp__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicTestHp;
/* prettier-ignore-end */
