/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fDd2G34bQHvh5ANU7bqHFd
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantsfwlxpTZnXniN } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: fwlxpTZnXniN/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsfwlxpTZnXniN
});
